# Setup
title:            'SOKI'
tagline:          'Blog by Soki'
description:      'Developing Space'
url:              'https://soki1229.github.io'
baseurl:          '/myspace'
paginate:         5

# About and contact
author:
  name:           'Philip Kim'
  url:            

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-spaceship

# Custom vars
version:          3.0.0

# Google Analytics
google_analytics: 'G-FPWXV8D0JH'
