# Setup
title:            Soki
tagline:          'Space Reporting Backtrace'
description:      'Work hard to work less. Made by soki.'
url:              soki1229.github.io
baseurl:          '/myspace'
paginate:         5

# About and contact
author:
  name:           'Philip Kim'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0


