# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Blog Space
tagline:          'A Jekyll theme'
description:      'Work hard to be less needed. space provided by soki. Made by
# <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              soki1229.github.io
baseurl:          /myspace

author:
  name:           'Philip Kim'
  url:            

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/poole/hyde
